import type { ItemDefBase } from './itemTypes';

type CatalogEntry = ItemDefBase & { id: string };

function I(entry: CatalogEntry): CatalogEntry {
  return entry;
}

/** Catálogo completo — chave = id do item. */
export const ITEM_CATALOG = {
  // — Legado (loot procedural antigo) —
  scrap: I({
    id: 'scrap',
    label: 'Sucata',
    rarity: 'common',
    category: 'legacy',
    weight: 1,
    maxStack: 8,
    description: 'Metal e plásticos partidos. Crafting básico.',
  }),
  cloth: I({
    id: 'cloth',
    label: 'Pano',
    rarity: 'common',
    category: 'consumable',
    weight: 1,
    maxStack: 6,
    description: 'Ligadura improvisada — estanca sangramento.',
    consumable: { uses: 1, effect: 'Estanca sangramento' },
  }),
  supplies: I({
    id: 'supplies',
    label: 'Suprimentos',
    rarity: 'rare',
    category: 'legacy',
    weight: 2,
    maxStack: 4,
    description: 'Comida, água ou material médico genérico.',
  }),
  rare_parts: I({
    id: 'rare_parts',
    label: 'Peças raras',
    rarity: 'legendary',
    category: 'legacy',
    weight: 3,
    maxStack: 2,
    description: 'Componentes escassos para upgrades avançados.',
  }),

  // — 1. Consumíveis —
  bottled_water: I({
    id: 'bottled_water',
    label: 'Água engarrafada',
    rarity: 'common',
    category: 'consumable',
    weight: 0.5,
    maxStack: 6,
    description: 'Recupera 15 hidratação.',
    consumable: { uses: 1, effect: '+15 hidratação' },
  }),
  canned_food: I({
    id: 'canned_food',
    label: 'Comida enlatada',
    rarity: 'common',
    category: 'consumable',
    weight: 0.4,
    maxStack: 6,
    description: 'Recupera 20 fome.',
    consumable: { uses: 1, effect: '+20 fome' },
  }),
  bandage: I({
    id: 'bandage',
    label: 'Bandagem',
    rarity: 'common',
    category: 'consumable',
    weight: 0.1,
    maxStack: 10,
    description: 'Remove sangramento e cura 8 HP.',
    consumable: { uses: 1, effect: 'Remove sangramento · +8 HP' },
  }),
  painkiller: I({
    id: 'painkiller',
    label: 'Analgésico',
    rarity: 'common',
    category: 'consumable',
    weight: 0.05,
    maxStack: 10,
    description: 'Reduz penalidade de ferimento por 60 s.',
    consumable: { uses: 1, effect: '− penalidade ferimento (60 s)' },
  }),
  antiseptic: I({
    id: 'antiseptic',
    label: 'Antisséptico',
    rarity: 'common',
    category: 'consumable',
    weight: 0.1,
    maxStack: 8,
    description: 'Reduz risco de infecção.',
    consumable: { uses: 1, effect: '− risco de infecção' },
  }),
  premium_canned_meat: I({
    id: 'premium_canned_meat',
    label: 'Carne enlatada premium',
    rarity: 'uncommon',
    category: 'consumable',
    weight: 0.5,
    maxStack: 5,
    description: 'Recupera 35 fome.',
    consumable: { uses: 1, effect: '+35 fome' },
  }),
  basic_medkit: I({
    id: 'basic_medkit',
    label: 'Kit médico básico',
    rarity: 'uncommon',
    category: 'consumable',
    weight: 0.6,
    maxStack: 3,
    description: 'Cura 30 HP e trata ferimentos leves.',
    consumable: { uses: 1, effect: '+30 HP · trata ferimentos leves' },
  }),
  antibiotic: I({
    id: 'antibiotic',
    label: 'Antibiótico',
    rarity: 'uncommon',
    category: 'consumable',
    weight: 0.05,
    maxStack: 5,
    description: 'Trata infecção.',
    consumable: { uses: 1, effect: 'Remove infecção' },
  }),
  energy_drink: I({
    id: 'energy_drink',
    label: 'Bebida energética',
    rarity: 'uncommon',
    category: 'consumable',
    weight: 0.3,
    maxStack: 5,
    description: '+15% velocidade por 90 s; reduz fadiga.',
    consumable: { uses: 1, effect: '+15% velocidade (90 s)' },
  }),
  military_mre: I({
    id: 'military_mre',
    label: 'Comida militar MRE',
    rarity: 'rare',
    category: 'consumable',
    weight: 0.6,
    maxStack: 4,
    description: 'Recupera 55 fome e 10 energia.',
    consumable: { uses: 1, effect: '+55 fome · +10 energia' },
  }),
  surgical_kit: I({
    id: 'surgical_kit',
    label: 'Kit cirúrgico',
    rarity: 'rare',
    category: 'consumable',
    weight: 1.0,
    maxStack: 2,
    description: 'Trata ferimentos graves.',
    consumable: { uses: 1, effect: 'Trata ferimentos graves' },
  }),
  stimulant: I({
    id: 'stimulant',
    label: 'Estimulante',
    rarity: 'rare',
    category: 'consumable',
    weight: 0.1,
    maxStack: 3,
    description: '+1 AP por 2 turnos; depois gera fadiga.',
    consumable: { uses: 1, effect: '+1 AP (2 turnos) · fadiga depois' },
  }),
  adrenaline_syringe: I({
    id: 'adrenaline_syringe',
    label: 'Adrenalina',
    rarity: 'super_rare',
    category: 'consumable',
    weight: 0.1,
    maxStack: 2,
    description: 'Impede incapacitação por 20 s.',
    consumable: { uses: 1, effect: 'Anti-incapacitação (20 s)' },
  }),
  experimental_antiviral: I({
    id: 'experimental_antiviral',
    label: 'Antiviral experimental',
    rarity: 'ultra_rare',
    category: 'consumable',
    weight: 0.1,
    maxStack: 1,
    description: 'Remove infecção avançada.',
    consumable: { uses: 1, effect: 'Remove infecção avançada' },
  }),
  regenerative_serum: I({
    id: 'regenerative_serum',
    label: 'Soro regenerativo',
    rarity: 'ultra_rare',
    category: 'consumable',
    weight: 0.2,
    maxStack: 1,
    description: 'Cura 60 HP gradualmente.',
    consumable: { uses: 1, effect: '+60 HP (gradual)' },
  }),
  experimental_nanomed: I({
    id: 'experimental_nanomed',
    label: 'Nanomedicina experimental',
    rarity: 'top_secret',
    category: 'consumable',
    weight: 0.1,
    maxStack: 1,
    description: 'Cura quase completamente e remove ferimentos.',
    consumable: { uses: 1, effect: 'Cura total · remove ferimentos' },
  }),

  // — 2. Componentes —
  scrap_iron: I({
    id: 'scrap_iron',
    label: 'Ferro-velho',
    rarity: 'common',
    category: 'component',
    weight: 0.2,
    maxStack: 50,
    description: 'Material universal para upgrades, reparos e crafting.',
  }),
  wood: I({
    id: 'wood',
    label: 'Madeira',
    rarity: 'common',
    category: 'component',
    weight: 0.5,
    maxStack: 30,
    description: 'Construção, barricadas e crafting.',
  }),
  fabric: I({
    id: 'fabric',
    label: 'Tecido',
    rarity: 'common',
    category: 'component',
    weight: 0.1,
    maxStack: 30,
    description: 'Roupas, bandagens e equipamentos.',
  }),
  plastic: I({
    id: 'plastic',
    label: 'Plástico',
    rarity: 'common',
    category: 'component',
    weight: 0.1,
    maxStack: 30,
    description: 'Crafting geral.',
  }),
  glass: I({
    id: 'glass',
    label: 'Vidro',
    rarity: 'common',
    category: 'component',
    weight: 0.2,
    maxStack: 20,
    description: 'Construção e equipamentos.',
  }),
  rubber: I({
    id: 'rubber',
    label: 'Borracha',
    rarity: 'common',
    category: 'component',
    weight: 0.2,
    maxStack: 20,
    description: 'Pneus, equipamentos e reparos.',
  }),
  mechanical_parts: I({
    id: 'mechanical_parts',
    label: 'Peças mecânicas',
    rarity: 'uncommon',
    category: 'component',
    weight: 0.4,
    maxStack: 20,
    description: 'Reparação de armas e máquinas.',
  }),
  electrical_components: I({
    id: 'electrical_components',
    label: 'Componentes elétricos',
    rarity: 'uncommon',
    category: 'component',
    weight: 0.1,
    maxStack: 20,
    description: 'Geradores, rádios e electrónica.',
  }),
  wiring: I({
    id: 'wiring',
    label: 'Fiação',
    rarity: 'uncommon',
    category: 'component',
    weight: 0.2,
    maxStack: 20,
    description: 'Instalações eléctricas.',
  }),
  hydraulic_components: I({
    id: 'hydraulic_components',
    label: 'Componentes hidráulicos',
    rarity: 'uncommon',
    category: 'component',
    weight: 0.4,
    maxStack: 15,
    description: 'Água e infra-estrutura.',
  }),
  metal_alloy: I({
    id: 'metal_alloy',
    label: 'Liga metálica',
    rarity: 'rare',
    category: 'component',
    weight: 0.5,
    maxStack: 15,
    description: 'Equipamentos avançados.',
  }),
  advanced_circuit: I({
    id: 'advanced_circuit',
    label: 'Circuito avançado',
    rarity: 'rare',
    category: 'component',
    weight: 0.1,
    maxStack: 10,
    description: 'Equipamentos tecnológicos.',
  }),
  military_component: I({
    id: 'military_component',
    label: 'Componente militar',
    rarity: 'super_rare',
    category: 'component',
    weight: 0.2,
    maxStack: 5,
    description: 'Equipamentos militares e armas avançadas.',
  }),
  advanced_microprocessor: I({
    id: 'advanced_microprocessor',
    label: 'Microprocessador avançado',
    rarity: 'ultra_rare',
    category: 'component',
    weight: 0.05,
    maxStack: 3,
    description: 'Tecnologia avançada.',
  }),
  unknown_tech_core: I({
    id: 'unknown_tech_core',
    label: 'Núcleo tecnológico desconhecido',
    rarity: 'top_secret',
    category: 'component',
    weight: 0.1,
    maxStack: 1,
    description: 'Crafting de equipamentos experimentais.',
  }),

  // — 3. Utilidade —
  flashlight: I({
    id: 'flashlight',
    label: 'Lanterna',
    rarity: 'common',
    category: 'utility',
    weight: 0.3,
    maxStack: 1,
    description: 'Ilumina ambientes escuros.',
    equip: { durability: 100, effect: 'Iluminação' },
  }),
  utility_knife: I({
    id: 'utility_knife',
    label: 'Faca utilitária',
    rarity: 'common',
    category: 'utility',
    weight: 0.2,
    maxStack: 1,
    description: 'Cortar, abrir embalagens e pequenas tarefas.',
    equip: { durability: 80 },
  }),
  crowbar: I({
    id: 'crowbar',
    label: 'Pé de cabra',
    rarity: 'common',
    category: 'utility',
    weight: 2.0,
    maxStack: 1,
    description: 'Abre portas e caixas determinadas.',
    equip: { durability: 100 },
    weapon: {
      damageMin: 8,
      damageMax: 16,
      cooldownSec: 1.1,
      range: 1,
      noise: 6,
      weaponType: 'contundente',
      durability: 130,
    },
  }),
  canteen: I({
    id: 'canteen',
    label: 'Cantil',
    rarity: 'common',
    category: 'utility',
    weight: 0.3,
    maxStack: 1,
    description: '+2 capacidade de água.',
    equip: { durability: 100, effect: '+2 capacidade água' },
  }),
  school_backpack: I({
    id: 'school_backpack',
    label: 'Mochila escolar',
    rarity: 'common',
    category: 'backpack',
    weight: 0.5,
    maxStack: 1,
    description: '+8 capacidade de carga.',
    equip: { capacityBonus: 8, noiseMod: 1, durability: 100 },
  }),
  tool_kit: I({
    id: 'tool_kit',
    label: 'Kit de ferramentas',
    rarity: 'uncommon',
    category: 'utility',
    weight: 3.0,
    maxStack: 1,
    description: 'Permite reparos básicos.',
    equip: { durability: 50, effect: 'Reparos básicos' },
  }),
  binoculars: I({
    id: 'binoculars',
    label: 'Binóculo',
    rarity: 'uncommon',
    category: 'accessory',
    weight: 0.8,
    maxStack: 1,
    description: '+20% raio de visão.',
    equip: { perceptionMod: 2, durability: 100, effect: '+20% visão' },
  }),
  portable_radio: I({
    id: 'portable_radio',
    label: 'Rádio portátil',
    rarity: 'uncommon',
    category: 'utility',
    weight: 0.5,
    maxStack: 1,
    description: 'Detecta transmissões e eventos.',
    equip: { durability: 100 },
  }),
  pliers: I({
    id: 'pliers',
    label: 'Alicate',
    rarity: 'uncommon',
    category: 'utility',
    weight: 0.4,
    maxStack: 1,
    description: 'Corta cercas e fios.',
    equip: { durability: 100 },
  }),
  wrench: I({
    id: 'wrench',
    label: 'Chave inglesa',
    rarity: 'uncommon',
    category: 'utility',
    weight: 1.5,
    maxStack: 1,
    description: 'Reparos mecânicos.',
    equip: { durability: 100 },
  }),
  regional_map: I({
    id: 'regional_map',
    label: 'Mapa regional',
    rarity: 'uncommon',
    category: 'utility',
    weight: 0.1,
    maxStack: 1,
    description: 'Revela parte da região. Uso único.',
    consumable: { uses: 1, effect: 'Revela região' },
  }),
  portable_purifier: I({
    id: 'portable_purifier',
    label: 'Purificador portátil',
    rarity: 'rare',
    category: 'utility',
    weight: 2.0,
    maxStack: 1,
    description: 'Purifica água contaminada.',
    equip: { durability: 40 },
  }),
  electronics_kit: I({
    id: 'electronics_kit',
    label: 'Kit electrónico',
    rarity: 'rare',
    category: 'utility',
    weight: 2.5,
    maxStack: 1,
    description: 'Repara equipamentos eléctricos.',
    equip: { durability: 40 },
  }),
  military_radio: I({
    id: 'military_radio',
    label: 'Rádio militar',
    rarity: 'rare',
    category: 'utility',
    weight: 1.0,
    maxStack: 1,
    description: 'Detecta grupos, transmissões e eventos.',
    equip: { durability: 150 },
  }),
  military_gps: I({
    id: 'military_gps',
    label: 'GPS militar',
    rarity: 'super_rare',
    category: 'utility',
    weight: 0.3,
    maxStack: 1,
    description: 'Navegação precisa.',
    equip: { durability: 200, effect: 'GPS / navegação' },
  }),
  professional_lockpick_kit: I({
    id: 'professional_lockpick_kit',
    label: 'Kit de arrombamento profissional',
    rarity: 'super_rare',
    category: 'utility',
    weight: 1.0,
    maxStack: 1,
    description: 'Abre fechaduras complexas em silêncio.',
    equip: { durability: 40, stealthMod: 2 },
  }),
  experimental_scanner: I({
    id: 'experimental_scanner',
    label: 'Scanner experimental',
    rarity: 'ultra_rare',
    category: 'utility',
    weight: 0.4,
    maxStack: 1,
    description: 'Detecta criaturas e objectos através de paredes finas.',
    equip: { durability: 100 },
  }),
  unknown_comm_device: I({
    id: 'unknown_comm_device',
    label: 'Dispositivo de comunicação desconhecido',
    rarity: 'top_secret',
    category: 'utility',
    weight: 0.2,
    maxStack: 1,
    description: 'Detecta transmissões especiais em grande distância.',
    equip: { durability: 300 },
  }),

  // — 4. Armas brancas —
  knife_melee: I({
    id: 'knife_melee',
    label: 'Faca',
    rarity: 'common',
    category: 'melee_weapon',
    weight: 0.3,
    maxStack: 1,
    description: 'Arma branca silenciosa.',
    weapon: {
      damageMin: 3,
      damageMax: 8,
      cooldownSec: 0.7,
      range: 1,
      noise: 2,
      weaponType: 'cortante',
      durability: 100,
    },
  }),
  baton: I({
    id: 'baton',
    label: 'Bastão',
    rarity: 'common',
    category: 'melee_weapon',
    weight: 1.2,
    maxStack: 1,
    description: 'Contundente.',
    weapon: {
      damageMin: 5,
      damageMax: 11,
      cooldownSec: 1.0,
      range: 1,
      noise: 5,
      weaponType: 'contundente',
      durability: 120,
    },
  }),
  baseball_bat: I({
    id: 'baseball_bat',
    label: 'Taco de beisebol',
    rarity: 'common',
    category: 'melee_weapon',
    weight: 1.5,
    maxStack: 1,
    description: 'Contundente.',
    weapon: {
      damageMin: 7,
      damageMax: 15,
      cooldownSec: 1.2,
      range: 1,
      noise: 7,
      weaponType: 'contundente',
      durability: 110,
    },
  }),
  axe: I({
    id: 'axe',
    label: 'Machado',
    rarity: 'uncommon',
    category: 'melee_weapon',
    weight: 2.5,
    maxStack: 1,
    description: 'Cortante.',
    weapon: {
      damageMin: 12,
      damageMax: 24,
      cooldownSec: 1.5,
      range: 1,
      noise: 9,
      weaponType: 'cortante',
      durability: 120,
    },
  }),
  machete: I({
    id: 'machete',
    label: 'Facão',
    rarity: 'uncommon',
    category: 'melee_weapon',
    weight: 1.3,
    maxStack: 1,
    description: 'Cortante.',
    weapon: {
      damageMin: 10,
      damageMax: 20,
      cooldownSec: 0.9,
      range: 1,
      noise: 6,
      weaponType: 'cortante',
      durability: 110,
    },
  }),
  sledgehammer: I({
    id: 'sledgehammer',
    label: 'Marreta',
    rarity: 'rare',
    category: 'melee_weapon',
    weight: 4.0,
    maxStack: 1,
    description: 'Contundente / atordoante.',
    weapon: {
      damageMin: 18,
      damageMax: 35,
      cooldownSec: 2.0,
      range: 1,
      noise: 12,
      weaponType: 'contundente',
      durability: 140,
      traits: ['atordoamento'],
    },
  }),
  katana: I({
    id: 'katana',
    label: 'Katana',
    rarity: 'rare',
    category: 'melee_weapon',
    weight: 1.3,
    maxStack: 1,
    description: 'Cortante.',
    weapon: {
      damageMin: 16,
      damageMax: 30,
      cooldownSec: 0.8,
      range: 1,
      noise: 5,
      weaponType: 'cortante',
      durability: 100,
    },
  }),
  improvised_spear: I({
    id: 'improvised_spear',
    label: 'Lança improvisada',
    rarity: 'rare',
    category: 'melee_weapon',
    weight: 2.0,
    maxStack: 1,
    description: 'Perfurante, alcance 2.',
    weapon: {
      damageMin: 14,
      damageMax: 28,
      cooldownSec: 1.3,
      range: 2,
      noise: 5,
      weaponType: 'perfurante',
      durability: 90,
    },
  }),
  tactical_axe: I({
    id: 'tactical_axe',
    label: 'Machado tático',
    rarity: 'super_rare',
    category: 'melee_weapon',
    weight: 2.2,
    maxStack: 1,
    description: 'Cortante.',
    weapon: {
      damageMin: 20,
      damageMax: 38,
      cooldownSec: 1.1,
      range: 1,
      noise: 7,
      weaponType: 'cortante',
      durability: 150,
    },
  }),
  military_spear: I({
    id: 'military_spear',
    label: 'Lança militar',
    rarity: 'ultra_rare',
    category: 'melee_weapon',
    weight: 2.5,
    maxStack: 1,
    description: 'Perfurante, alcance 2.',
    weapon: {
      damageMin: 25,
      damageMax: 45,
      cooldownSec: 1.1,
      range: 2,
      noise: 4,
      weaponType: 'perfurante',
      durability: 160,
    },
  }),
  experimental_blade: I({
    id: 'experimental_blade',
    label: 'Lâmina experimental',
    rarity: 'top_secret',
    category: 'melee_weapon',
    weight: 1.0,
    maxStack: 1,
    description: 'Cortante especial.',
    weapon: {
      damageMin: 30,
      damageMax: 55,
      cooldownSec: 0.6,
      range: 1,
      noise: 2,
      weaponType: 'cortante',
      durability: 200,
      traits: ['execução'],
    },
  }),

  // — 5. Armas de fogo —
  revolver_38: I({
    id: 'revolver_38',
    label: 'Revólver .38',
    rarity: 'common',
    category: 'firearm',
    weight: 1.0,
    maxStack: 1,
    description: 'Semiautomática.',
    weapon: {
      damageMin: 18,
      damageMax: 30,
      cooldownSec: 1.1,
      range: 8,
      noise: 18,
      accuracy: 0.72,
      weaponType: 'semiautomática',
      magSize: 6,
      ammoType: '.38',
    },
  }),
  pistol_9mm: I({
    id: 'pistol_9mm',
    label: 'Pistola 9mm',
    rarity: 'common',
    category: 'firearm',
    weight: 0.9,
    maxStack: 1,
    description: 'Semiautomática.',
    weapon: {
      damageMin: 14,
      damageMax: 24,
      cooldownSec: 0.7,
      range: 8,
      noise: 17,
      accuracy: 0.78,
      weaponType: 'semiautomática',
      magSize: 8,
      ammoType: '9mm',
    },
  }),
  old_shotgun: I({
    id: 'old_shotgun',
    label: 'Espingarda velha',
    rarity: 'common',
    category: 'firearm',
    weight: 3.2,
    maxStack: 1,
    description: 'Dano em área.',
    weapon: {
      damageMin: 35,
      damageMax: 60,
      cooldownSec: 2.2,
      range: 6,
      noise: 35,
      accuracy: 0.62,
      weaponType: 'área',
      magSize: 2,
      ammoType: 'cal.12',
    },
  }),
  police_pistol: I({
    id: 'police_pistol',
    label: 'Pistola policial',
    rarity: 'uncommon',
    category: 'firearm',
    weight: 1.0,
    maxStack: 1,
    description: 'Semiautomática.',
    weapon: {
      damageMin: 16,
      damageMax: 27,
      cooldownSec: 0.6,
      range: 9,
      noise: 17,
      accuracy: 0.84,
      weaponType: 'semiautomática',
      magSize: 12,
      ammoType: '9mm',
    },
  }),
  improvised_smg: I({
    id: 'improvised_smg',
    label: 'SMG improvisada',
    rarity: 'uncommon',
    category: 'firearm',
    weight: 2.5,
    maxStack: 1,
    description: 'Rajada / automática.',
    weapon: {
      damageMin: 10,
      damageMax: 17,
      cooldownSec: 0.18,
      range: 8,
      noise: 25,
      accuracy: 0.65,
      weaponType: 'automática',
      magSize: 25,
      ammoType: '9mm',
    },
  }),
  hunting_rifle: I({
    id: 'hunting_rifle',
    label: 'Rifle de caça',
    rarity: 'uncommon',
    category: 'firearm',
    weight: 3.5,
    maxStack: 1,
    description: 'Precisão.',
    weapon: {
      damageMin: 35,
      damageMax: 65,
      cooldownSec: 1.8,
      range: 18,
      noise: 28,
      accuracy: 0.91,
      weaponType: 'precisão',
      magSize: 5,
      ammoType: '7.62',
    },
  }),
  police_shotgun: I({
    id: 'police_shotgun',
    label: 'Escopeta policial',
    rarity: 'rare',
    category: 'firearm',
    weight: 3.4,
    maxStack: 1,
    description: 'Dano em área.',
    weapon: {
      damageMin: 45,
      damageMax: 75,
      cooldownSec: 1.8,
      range: 7,
      noise: 38,
      accuracy: 0.68,
      weaponType: 'área',
      magSize: 6,
      ammoType: 'cal.12',
    },
  }),
  tactical_pistol: I({
    id: 'tactical_pistol',
    label: 'Pistola tática',
    rarity: 'rare',
    category: 'firearm',
    weight: 1.0,
    maxStack: 1,
    description: 'Semiautomática.',
    weapon: {
      damageMin: 18,
      damageMax: 30,
      cooldownSec: 0.5,
      range: 10,
      noise: 16,
      accuracy: 0.9,
      weaponType: 'semiautomática',
      magSize: 15,
      ammoType: '9mm',
    },
  }),
  silenced_pistol: I({
    id: 'silenced_pistol',
    label: 'Pistola silenciada',
    rarity: 'rare',
    category: 'firearm',
    weight: 1.2,
    maxStack: 1,
    description: 'Silenciosa.',
    weapon: {
      damageMin: 15,
      damageMax: 25,
      cooldownSec: 0.65,
      range: 9,
      noise: 7,
      accuracy: 0.86,
      weaponType: 'silenciosa',
      magSize: 12,
      ammoType: '9mm',
    },
  }),
  assault_rifle: I({
    id: 'assault_rifle',
    label: 'Rifle de assalto',
    rarity: 'rare',
    category: 'firearm',
    weight: 3.6,
    maxStack: 1,
    description: 'Automática.',
    weapon: {
      damageMin: 20,
      damageMax: 34,
      cooldownSec: 0.2,
      range: 15,
      noise: 32,
      accuracy: 0.76,
      weaponType: 'automática',
      magSize: 30,
      ammoType: '5.56',
    },
  }),
  sniper_rifle: I({
    id: 'sniper_rifle',
    label: 'Rifle de precisão',
    rarity: 'super_rare',
    category: 'firearm',
    weight: 4.5,
    maxStack: 1,
    description: 'Precisão / perfurante.',
    weapon: {
      damageMin: 65,
      damageMax: 110,
      cooldownSec: 2.5,
      range: 25,
      noise: 34,
      accuracy: 0.97,
      weaponType: 'precisão',
      magSize: 5,
      ammoType: '7.62',
      traits: ['perfurante'],
    },
  }),
  tactical_smg: I({
    id: 'tactical_smg',
    label: 'SMG tática',
    rarity: 'super_rare',
    category: 'firearm',
    weight: 2.8,
    maxStack: 1,
    description: 'Automática.',
    weapon: {
      damageMin: 13,
      damageMax: 22,
      cooldownSec: 0.13,
      range: 11,
      noise: 24,
      accuracy: 0.82,
      weaponType: 'automática',
      magSize: 32,
      ammoType: '9mm',
    },
  }),
  military_rifle: I({
    id: 'military_rifle',
    label: 'Rifle militar',
    rarity: 'ultra_rare',
    category: 'firearm',
    weight: 3.8,
    maxStack: 1,
    description: 'Automática.',
    weapon: {
      damageMin: 28,
      damageMax: 45,
      cooldownSec: 0.16,
      range: 18,
      noise: 30,
      accuracy: 0.88,
      weaponType: 'automática',
      magSize: 30,
      ammoType: '5.56',
    },
  }),
  auto_shotgun: I({
    id: 'auto_shotgun',
    label: 'Escopeta automática',
    rarity: 'ultra_rare',
    category: 'firearm',
    weight: 4.0,
    maxStack: 1,
    description: 'Área / automática.',
    weapon: {
      damageMin: 40,
      damageMax: 68,
      cooldownSec: 0.6,
      range: 8,
      noise: 40,
      accuracy: 0.72,
      weaponType: 'automática',
      magSize: 8,
      ammoType: 'cal.12',
    },
  }),
  experimental_rifle: I({
    id: 'experimental_rifle',
    label: 'Rifle experimental',
    rarity: 'top_secret',
    category: 'firearm',
    weight: 3.5,
    maxStack: 1,
    description: 'Rajada / perfurante.',
    weapon: {
      damageMin: 40,
      damageMax: 65,
      cooldownSec: 0.12,
      range: 22,
      noise: 20,
      accuracy: 0.94,
      weaponType: 'rajada',
      magSize: 40,
      ammoType: 'experimental',
      traits: ['perfurante'],
    },
  }),

  // — 6. Explosivas / especiais —
  molotov: I({
    id: 'molotov',
    label: 'Molotov',
    rarity: 'uncommon',
    category: 'explosive',
    weight: 0.5,
    maxStack: 4,
    description: 'Incendeia área (DoT).',
    weapon: {
      damageMin: 10,
      damageMax: 20,
      cooldownSec: 3,
      range: 7,
      noise: 15,
      weaponType: 'incendiária',
      traits: ['DoT', 'área'],
    },
  }),
  improvised_grenade: I({
    id: 'improvised_grenade',
    label: 'Granada improvisada',
    rarity: 'rare',
    category: 'explosive',
    weight: 0.5,
    maxStack: 3,
    description: 'Explosiva em área.',
    weapon: {
      damageMin: 35,
      damageMax: 70,
      cooldownSec: 4,
      range: 8,
      noise: 40,
      weaponType: 'explosiva',
      traits: ['área'],
    },
  }),
  frag_grenade: I({
    id: 'frag_grenade',
    label: 'Granada de fragmentação',
    rarity: 'rare',
    category: 'explosive',
    weight: 0.4,
    maxStack: 3,
    description: 'Fragmentos / perfurante.',
    weapon: {
      damageMin: 45,
      damageMax: 85,
      cooldownSec: 4,
      range: 10,
      noise: 45,
      weaponType: 'explosiva',
      traits: ['perfurante', 'área'],
    },
  }),
  incendiary_grenade: I({
    id: 'incendiary_grenade',
    label: 'Granada incendiária',
    rarity: 'super_rare',
    category: 'explosive',
    weight: 0.5,
    maxStack: 2,
    description: 'Fogo persistente.',
    weapon: {
      damageMin: 15,
      damageMax: 30,
      cooldownSec: 4,
      range: 9,
      noise: 35,
      weaponType: 'incendiária',
      traits: ['DoT', 'área'],
    },
  }),
  improvised_mine: I({
    id: 'improvised_mine',
    label: 'Mina improvisada',
    rarity: 'super_rare',
    category: 'explosive',
    weight: 1.5,
    maxStack: 2,
    description: 'Ativação por proximidade.',
    weapon: {
      damageMin: 60,
      damageMax: 120,
      cooldownSec: 0,
      range: 1,
      noise: 50,
      weaponType: 'explosiva',
      traits: ['proximidade'],
    },
  }),
  military_mine: I({
    id: 'military_mine',
    label: 'Mina militar',
    rarity: 'ultra_rare',
    category: 'explosive',
    weight: 2.0,
    maxStack: 1,
    description: 'Grande explosão em área.',
    weapon: {
      damageMin: 100,
      damageMax: 180,
      cooldownSec: 0,
      range: 1,
      noise: 60,
      weaponType: 'explosiva',
      traits: ['área', 'proximidade'],
    },
  }),
  flamethrower: I({
    id: 'flamethrower',
    label: 'Lança-chamas',
    rarity: 'ultra_rare',
    category: 'explosive',
    weight: 8.0,
    maxStack: 1,
    description: 'DoT / área contínua.',
    weapon: {
      damageMin: 8,
      damageMax: 15,
      cooldownSec: 0.1,
      range: 6,
      noise: 25,
      weaponType: 'incendiária',
      traits: ['DoT', 'área'],
    },
  }),
  experimental_incendiary: I({
    id: 'experimental_incendiary',
    label: 'Dispositivo incendiário experimental',
    rarity: 'top_secret',
    category: 'explosive',
    weight: 4.0,
    maxStack: 1,
    description: 'Fogo persistente em área.',
    weapon: {
      damageMin: 20,
      damageMax: 35,
      cooldownSec: 0.1,
      range: 10,
      noise: 20,
      weaponType: 'incendiária',
      traits: ['DoT', 'área'],
    },
  }),

  // — 7. Equipamentos de protecção —
  cap: I({
    id: 'cap',
    label: 'Boné',
    rarity: 'common',
    category: 'armor',
    weight: 0.1,
    maxStack: 1,
    description: '+1 percepção.',
    equip: { armor: 0, noiseMod: -1, perceptionMod: 1, durability: 50 },
  }),
  bike_helmet: I({
    id: 'bike_helmet',
    label: 'Capacete de bicicleta',
    rarity: 'common',
    category: 'armor',
    weight: 0.4,
    maxStack: 1,
    description: 'Protecção leve.',
    equip: { armor: 2, durability: 70 },
  }),
  reinforced_jacket: I({
    id: 'reinforced_jacket',
    label: 'Jaqueta reforçada',
    rarity: 'common',
    category: 'armor',
    weight: 1.5,
    maxStack: 1,
    description: 'Protecção básica.',
    equip: { armor: 2, noiseMod: 1, durability: 80 },
  }),
  improvised_vest: I({
    id: 'improvised_vest',
    label: 'Colete improvisado',
    rarity: 'common',
    category: 'armor',
    weight: 2.5,
    maxStack: 1,
    description: 'Protecção improvisada.',
    equip: { armor: 3, noiseMod: 2, durability: 80 },
  }),
  construction_helmet: I({
    id: 'construction_helmet',
    label: 'Capacete de construção',
    rarity: 'uncommon',
    category: 'armor',
    weight: 1.0,
    maxStack: 1,
    description: 'Resistência a impacto.',
    equip: { armor: 4, noiseMod: 1, durability: 100, effect: 'Anti-impacto' },
  }),
  police_vest: I({
    id: 'police_vest',
    label: 'Colete policial',
    rarity: 'uncommon',
    category: 'armor',
    weight: 4.0,
    maxStack: 1,
    description: 'Protecção balística leve.',
    equip: { armor: 6, noiseMod: 3, durability: 110 },
  }),
  stealth_jacket: I({
    id: 'stealth_jacket',
    label: 'Jaqueta furtiva',
    rarity: 'uncommon',
    category: 'armor',
    weight: 1.2,
    maxStack: 1,
    description: '+furtividade.',
    equip: { armor: 2, noiseMod: -3, stealthMod: 3, durability: 80 },
  }),
  tactical_helmet: I({
    id: 'tactical_helmet',
    label: 'Capacete tático',
    rarity: 'rare',
    category: 'armor',
    weight: 1.5,
    maxStack: 1,
    description: '+percepção.',
    equip: { armor: 7, noiseMod: 2, perceptionMod: 2, durability: 130 },
  }),
  tactical_vest: I({
    id: 'tactical_vest',
    label: 'Colete tático',
    rarity: 'rare',
    category: 'armor',
    weight: 5.0,
    maxStack: 1,
    description: '+2 slots acessórios.',
    equip: { armor: 9, noiseMod: 3, slotBonus: 2, durability: 130 },
  }),
  heavy_armor: I({
    id: 'heavy_armor',
    label: 'Armadura pesada',
    rarity: 'rare',
    category: 'armor',
    weight: 8.0,
    maxStack: 1,
    description: 'Grande protecção.',
    equip: { armor: 13, noiseMod: 7, durability: 150 },
  }),
  military_vest: I({
    id: 'military_vest',
    label: 'Colete militar',
    rarity: 'super_rare',
    category: 'armor',
    weight: 5.5,
    maxStack: 1,
    description: '+resistência.',
    equip: { armor: 12, noiseMod: 2, durability: 160, effect: '+resistência' },
  }),
  advanced_military_helmet: I({
    id: 'advanced_military_helmet',
    label: 'Capacete militar avançado',
    rarity: 'super_rare',
    category: 'armor',
    weight: 2.0,
    maxStack: 1,
    description: '+visão.',
    equip: { armor: 10, noiseMod: 2, perceptionMod: 3, durability: 160 },
  }),
  recon_armor: I({
    id: 'recon_armor',
    label: 'Armadura leve de reconhecimento',
    rarity: 'ultra_rare',
    category: 'armor',
    weight: 3.0,
    maxStack: 1,
    description: '+10% velocidade.',
    equip: {
      armor: 9,
      noiseMod: -3,
      speedMod: 0.1,
      durability: 180,
    },
  }),
  partial_exoskeleton: I({
    id: 'partial_exoskeleton',
    label: 'Exoesqueleto parcial',
    rarity: 'ultra_rare',
    category: 'armor',
    weight: 9.0,
    maxStack: 1,
    description: '+força / carga.',
    equip: { armor: 15, noiseMod: 1, durability: 220, effect: '+força · +carga' },
  }),
  experimental_armor: I({
    id: 'experimental_armor',
    label: 'Armadura experimental',
    rarity: 'top_secret',
    category: 'armor',
    weight: 6.0,
    maxStack: 1,
    description: 'Reduz dano e ruído.',
    equip: {
      armor: 18,
      noiseMod: -2,
      durability: 250,
      effect: 'Reduz dano e ruído',
    },
  }),

  // — 8. Mochilas —
  sports_backpack: I({
    id: 'sports_backpack',
    label: 'Mochila esportiva',
    rarity: 'common',
    category: 'backpack',
    weight: 0.7,
    maxStack: 1,
    description: '+10 capacidade.',
    equip: { capacityBonus: 10, noiseMod: 2, durability: 100 },
  }),
  trail_backpack: I({
    id: 'trail_backpack',
    label: 'Mochila de trilha',
    rarity: 'uncommon',
    category: 'backpack',
    weight: 1.0,
    maxStack: 1,
    description: '+16 capacidade.',
    equip: { capacityBonus: 16, noiseMod: 2, durability: 100 },
  }),
  military_backpack: I({
    id: 'military_backpack',
    label: 'Mochila militar',
    rarity: 'rare',
    category: 'backpack',
    weight: 1.5,
    maxStack: 1,
    description: '+22 capacidade · +1 slot.',
    equip: { capacityBonus: 22, noiseMod: 3, slotBonus: 1, durability: 120 },
  }),
  tactical_backpack: I({
    id: 'tactical_backpack',
    label: 'Mochila tática',
    rarity: 'super_rare',
    category: 'backpack',
    weight: 1.2,
    maxStack: 1,
    description: '+25 capacidade · +2 slots.',
    equip: { capacityBonus: 25, noiseMod: 1, slotBonus: 2, durability: 130 },
  }),
  expedition_backpack: I({
    id: 'expedition_backpack',
    label: 'Mochila de expedição',
    rarity: 'ultra_rare',
    category: 'backpack',
    weight: 1.0,
    maxStack: 1,
    description: '+30 capacidade · reduz peso de recursos.',
    equip: {
      capacityBonus: 30,
      durability: 140,
      effect: 'Recursos pesam menos',
    },
  }),
  experimental_load_system: I({
    id: 'experimental_load_system',
    label: 'Sistema de carga experimental',
    rarity: 'top_secret',
    category: 'backpack',
    weight: 0.8,
    maxStack: 1,
    description: '+35 capacidade · itens pesam 20% menos.',
    equip: {
      capacityBonus: 35,
      noiseMod: -1,
      durability: 160,
      effect: '−20% peso de recursos',
    },
  }),

  // — 9. Calçados —
  sneakers: I({
    id: 'sneakers',
    label: 'Tênis',
    rarity: 'common',
    category: 'footwear',
    weight: 0.6,
    maxStack: 1,
    description: 'Ruído −1.',
    equip: { noiseMod: -1, durability: 80 },
  }),
  common_boots: I({
    id: 'common_boots',
    label: 'Bota comum',
    rarity: 'common',
    category: 'footwear',
    weight: 1.0,
    maxStack: 1,
    description: '+1 protecção.',
    equip: { armor: 1, durability: 100 },
  }),
  work_boots: I({
    id: 'work_boots',
    label: 'Bota de trabalho',
    rarity: 'uncommon',
    category: 'footwear',
    weight: 1.4,
    maxStack: 1,
    description: '+2 protecção · +resistência.',
    equip: { armor: 2, durability: 120, effect: '+resistência' },
  }),
  military_boots: I({
    id: 'military_boots',
    label: 'Bota militar',
    rarity: 'rare',
    category: 'footwear',
    weight: 1.5,
    maxStack: 1,
    description: '+2 protecção · +5% resistência.',
    equip: { armor: 2, durability: 140, effect: '+5% resistência' },
  }),
  stealth_footwear: I({
    id: 'stealth_footwear',
    label: 'Calçado furtivo',
    rarity: 'super_rare',
    category: 'footwear',
    weight: 0.7,
    maxStack: 1,
    description: 'Ruído −4.',
    equip: { noiseMod: -4, stealthMod: 4, durability: 120 },
  }),
  recon_boots: I({
    id: 'recon_boots',
    label: 'Bota de reconhecimento',
    rarity: 'ultra_rare',
    category: 'footwear',
    weight: 1.0,
    maxStack: 1,
    description: 'Ruído −3 · velocidade +5%.',
    equip: { noiseMod: -3, speedMod: 0.05, durability: 160 },
  }),
  experimental_footwear: I({
    id: 'experimental_footwear',
    label: 'Calçado experimental',
    rarity: 'top_secret',
    category: 'footwear',
    weight: 0.6,
    maxStack: 1,
    description: 'Ruído −5 · velocidade +8%.',
    equip: { noiseMod: -5, speedMod: 0.08, durability: 200 },
  }),

  // — 10. Acessórios —
  watch: I({
    id: 'watch',
    label: 'Relógio',
    rarity: 'common',
    category: 'accessory',
    weight: 0.1,
    maxStack: 1,
    description: 'Mostra horário.',
    equip: { durability: 200, effect: 'Horário' },
  }),
  glasses: I({
    id: 'glasses',
    label: 'Óculos',
    rarity: 'common',
    category: 'accessory',
    weight: 0.1,
    maxStack: 1,
    description: '+1 percepção.',
    equip: { perceptionMod: 1, durability: 100 },
  }),
  tactical_flashlight: I({
    id: 'tactical_flashlight',
    label: 'Lanterna tática',
    rarity: 'uncommon',
    category: 'accessory',
    weight: 0.4,
    maxStack: 1,
    description: 'Iluminação +50%.',
    equip: { durability: 150, effect: '+50% iluminação' },
  }),
  simple_sight: I({
    id: 'simple_sight',
    label: 'Mira simples',
    rarity: 'uncommon',
    category: 'accessory',
    weight: 0.2,
    maxStack: 1,
    description: 'Precisão +3%.',
    equip: { durability: 100, effect: '+3% precisão' },
  }),
  holographic_sight: I({
    id: 'holographic_sight',
    label: 'Mira holográfica',
    rarity: 'rare',
    category: 'accessory',
    weight: 0.3,
    maxStack: 1,
    description: 'Precisão +7%.',
    equip: { durability: 150, effect: '+7% precisão' },
  }),
  suppressor: I({
    id: 'suppressor',
    label: 'Supressor',
    rarity: 'rare',
    category: 'accessory',
    weight: 0.5,
    maxStack: 1,
    description: 'Ruído −60% · dano −5%.',
    equip: { noiseMod: -6, durability: 100, effect: '−60% ruído · −5% dano' },
  }),
  telescopic_sight: I({
    id: 'telescopic_sight',
    label: 'Mira telescópica',
    rarity: 'super_rare',
    category: 'accessory',
    weight: 0.6,
    maxStack: 1,
    description: 'Precisão +12% · alcance +25%.',
    equip: { durability: 120, effect: '+12% precisão · +25% alcance' },
  }),
  military_suppressor: I({
    id: 'military_suppressor',
    label: 'Supressor militar',
    rarity: 'ultra_rare',
    category: 'accessory',
    weight: 0.5,
    maxStack: 1,
    description: 'Ruído −75% · dano −2%.',
    equip: { noiseMod: -8, durability: 180, effect: '−75% ruído · −2% dano' },
  }),
  experimental_optics: I({
    id: 'experimental_optics',
    label: 'Sistema óptico experimental',
    rarity: 'top_secret',
    category: 'accessory',
    weight: 0.4,
    maxStack: 1,
    description: '+20% precisão · +30% alcance.',
    equip: {
      durability: 250,
      effect: '+20% precisão · +30% alcance',
    },
  }),
} as const satisfies Record<string, CatalogEntry>;

export type ItemId = keyof typeof ITEM_CATALOG;
