import type { StructureDefinition } from './types';
import { DEFAULT_WEIGHTS } from './types';

const W = DEFAULT_WEIGHTS;

function def(partial: StructureDefinition): StructureDefinition {
  return {
    ...partial,
    scoreWeights: { ...W, ...partial.scoreWeights },
  };
}

export const STRUCTURE_DEFINITIONS: StructureDefinition[] = [
  def({
    id: 'hospital',
    label: 'Hospital',
    category: 'primary',
    footprint: { w: 8, h: 6 },
    color: 0xe74c3c,
    allowedZones: ['center', 'commercial', 'mixed', 'residential_med'],
    preferredRoadTypes: ['avenue', 'main'],
    minRoadAccess: 0.1,
    preferredDensity: ['high', 'medium'],
    rarity: 0.15,
    maxPerCity: 2,
    lotSizeRange: { min: 40, max: 999 },
    isCityAnchor: true,
    composition: [
      { childId: 'parking_lot', chance: 0.9, min: 1, max: 1 },
      { childId: 'depot', chance: 0.7, min: 0, max: 1 },
      { childId: 'generator', chance: 0.8, min: 0, max: 1 },
    ],
    scoreWeights: { ...W, road: 1.4, zone: 1.3, center: 0.8 },
    forbiddenNearby: [{ zone: 'industrial', maxDistance: 8, penalty: 30 }],
  }),
  def({
    id: 'clinic',
    label: 'Clínica',
    category: 'primary',
    footprint: { w: 5, h: 4 },
    color: 0xe67e22,
    allowedZones: ['commercial', 'mixed', 'residential_med', 'center'],
    preferredRoadTypes: ['avenue', 'street', 'main'],
    minRoadAccess: 0.1,
    preferredDensity: ['high', 'medium'],
    rarity: 0.4,
    maxPerCity: 4,
    lotSizeRange: { min: 20, max: 999 },
    isCityAnchor: true,
    composition: [{ childId: 'parking_lot', chance: 0.5, min: 0, max: 1 }],
    scoreWeights: W,
  }),
  def({
    id: 'pharmacy',
    label: 'Farmácia',
    category: 'primary',
    footprint: { w: 4, h: 3 },
    color: 0x2ecc71,
    allowedZones: ['commercial', 'mixed', 'residential_med', 'center'],
    preferredRoadTypes: ['street', 'avenue'],
    minRoadAccess: 0.1,
    preferredDensity: ['high', 'medium'],
    rarity: 0.55,
    maxPerCity: 6,
    lotSizeRange: { min: 12, max: 999 },
    scoreWeights: W,
  }),
  def({
    id: 'police',
    label: 'Delegacia',
    category: 'primary',
    footprint: { w: 6, h: 5 },
    color: 0x3498db,
    allowedZones: ['center', 'commercial', 'mixed'],
    preferredRoadTypes: ['avenue', 'main'],
    minRoadAccess: 0.15,
    preferredDensity: ['high', 'medium'],
    rarity: 0.2,
    maxPerCity: 2,
    lotSizeRange: { min: 30, max: 999 },
    isCityAnchor: true,
    composition: [{ childId: 'parking_lot', chance: 0.8, min: 0, max: 1 }],
    scoreWeights: { ...W, road: 1.3, zone: 1.2 },
  }),
  def({
    id: 'fire_station',
    label: 'Bombeiros',
    category: 'primary',
    footprint: { w: 7, h: 5 },
    color: 0xc0392b,
    allowedZones: ['mixed', 'industrial', 'commercial', 'center'],
    preferredRoadTypes: ['avenue', 'main'],
    minRoadAccess: 0.2,
    preferredDensity: ['medium', 'high'],
    rarity: 0.2,
    maxPerCity: 2,
    lotSizeRange: { min: 35, max: 999 },
    isCityAnchor: true,
    composition: [
      { childId: 'garage', chance: 0.8, min: 1, max: 1 },
      { childId: 'depot', chance: 0.5, min: 0, max: 1 },
    ],
    scoreWeights: W,
  }),
  def({
    id: 'school',
    label: 'Escola',
    category: 'primary',
    footprint: { w: 9, h: 7 },
    color: 0x5dade2,
    allowedZones: ['residential_med', 'residential_low', 'mixed', 'suburban'],
    preferredRoadTypes: ['avenue', 'street', 'main'],
    minRoadAccess: 0.12,
    preferredDensity: ['medium', 'low'],
    rarity: 0.25,
    maxPerCity: 3,
    lotSizeRange: { min: 50, max: 999 },
    isCityAnchor: true,
    composition: [{ childId: 'parking_lot', chance: 0.7, min: 0, max: 1 }],
    scoreWeights: W,
  }),
  def({
    id: 'public_building',
    label: 'Prédio público',
    category: 'primary',
    footprint: { w: 6, h: 6 },
    color: 0x7f8c8d,
    allowedZones: ['center', 'mixed', 'commercial'],
    preferredRoadTypes: ['avenue', 'main'],
    minRoadAccess: 0.12,
    preferredDensity: ['high', 'medium'],
    rarity: 0.3,
    maxPerCity: 3,
    lotSizeRange: { min: 30, max: 999 },
    scoreWeights: W,
  }),
  def({
    id: 'market',
    label: 'Mercado',
    category: 'primary',
    footprint: { w: 7, h: 6 },
    color: 0x27ae60,
    allowedZones: ['commercial', 'mixed', 'center', 'residential_med'],
    preferredRoadTypes: ['avenue', 'street', 'main'],
    minRoadAccess: 0.15,
    preferredDensity: ['high', 'medium'],
    rarity: 0.45,
    maxPerCity: 5,
    lotSizeRange: { min: 35, max: 999 },
    isCityAnchor: true,
    composition: [
      { childId: 'parking_lot', chance: 0.8, min: 0, max: 1 },
      { childId: 'depot', chance: 0.5, min: 0, max: 1 },
    ],
    scoreWeights: W,
  }),
  def({
    id: 'gas_station',
    label: 'Posto',
    category: 'primary',
    footprint: { w: 6, h: 5 },
    color: 0xf1c40f,
    allowedZones: ['commercial', 'periphery', 'industrial', 'suburban', 'mixed'],
    preferredRoadTypes: ['main', 'avenue', 'highway'],
    minRoadAccess: 0.2,
    preferredDensity: ['medium', 'low'],
    rarity: 0.4,
    maxPerCity: 4,
    lotSizeRange: { min: 25, max: 999 },
    isCityAnchor: true,
    composition: [
      { childId: 'convenience', chance: 0.85, min: 0, max: 1 },
      { childId: 'parking_lot', chance: 0.6, min: 0, max: 1 },
      { childId: 'workshop_annex', chance: 0.4, min: 0, max: 1 },
    ],
    scoreWeights: { ...W, road: 1.5 },
  }),
  def({
    id: 'restaurant',
    label: 'Restaurante',
    category: 'primary',
    footprint: { w: 4, h: 4 },
    color: 0xe91e63,
    allowedZones: ['commercial', 'mixed', 'center', 'residential_med'],
    preferredRoadTypes: ['street', 'avenue'],
    minRoadAccess: 0.1,
    preferredDensity: ['high', 'medium'],
    rarity: 0.7,
    lotSizeRange: { min: 12, max: 999 },
    scoreWeights: W,
  }),
  def({
    id: 'convenience',
    label: 'Conveniência',
    category: 'secondary',
    footprint: { w: 3, h: 3 },
    color: 0x1abc9c,
    allowedZones: [
      'commercial',
      'mixed',
      'residential_med',
      'suburban',
      'periphery',
    ],
    preferredRoadTypes: ['street', 'avenue', 'main'],
    minRoadAccess: 0.05,
    preferredDensity: ['medium', 'high', 'low'],
    rarity: 0.6,
    lotSizeRange: { min: 8, max: 999 },
    scoreWeights: W,
  }),
  def({
    id: 'hotel',
    label: 'Hotel',
    category: 'primary',
    footprint: { w: 7, h: 6 },
    color: 0xd4a017,
    allowedZones: ['center', 'commercial', 'mixed'],
    preferredRoadTypes: ['avenue', 'main'],
    minRoadAccess: 0.15,
    preferredDensity: ['high', 'medium'],
    rarity: 0.3,
    maxPerCity: 3,
    lotSizeRange: { min: 40, max: 999 },
    composition: [{ childId: 'parking_lot', chance: 0.85, min: 1, max: 1 }],
    scoreWeights: W,
  }),
  def({
    id: 'house',
    label: 'Casa',
    category: 'primary',
    footprint: { w: 4, h: 4 },
    color: 0xc4a574,
    allowedZones: [
      'residential_low',
      'residential_med',
      'suburban',
      'periphery',
      'rural',
    ],
    preferredRoadTypes: ['residential', 'street'],
    minRoadAccess: 0.05,
    preferredDensity: ['low', 'medium', 'sparse'],
    rarity: 1,
    lotSizeRange: { min: 12, max: 999 },
    composition: [
      { childId: 'garage', chance: 0.45, min: 0, max: 1 },
      { childId: 'shed_annex', chance: 0.25, min: 0, max: 1 },
    ],
    scoreWeights: W,
  }),
  def({
    id: 'apartment',
    label: 'Apartamento',
    category: 'primary',
    footprint: { w: 5, h: 6 },
    color: 0x8b9dc3,
    allowedZones: ['residential_med', 'mixed', 'center'],
    preferredRoadTypes: ['street', 'avenue'],
    minRoadAccess: 0.1,
    preferredDensity: ['high', 'medium'],
    rarity: 0.65,
    lotSizeRange: { min: 24, max: 999 },
    composition: [{ childId: 'parking_lot', chance: 0.5, min: 0, max: 1 }],
    scoreWeights: W,
  }),
  def({
    id: 'residential_block',
    label: 'Condomínio',
    category: 'primary',
    footprint: { w: 8, h: 8 },
    color: 0xa67c52,
    allowedZones: ['residential_med', 'suburban'],
    preferredRoadTypes: ['street', 'avenue'],
    minRoadAccess: 0.1,
    preferredDensity: ['medium'],
    rarity: 0.35,
    maxPerCity: 4,
    lotSizeRange: { min: 50, max: 999 },
    composition: [
      { childId: 'parking_lot', chance: 0.9, min: 1, max: 1 },
      { childId: 'storage', chance: 0.4, min: 0, max: 1 },
    ],
    scoreWeights: W,
  }),
  def({
    id: 'church',
    label: 'Igreja',
    category: 'primary',
    footprint: { w: 5, h: 6 },
    color: 0xd5dbdb,
    allowedZones: ['residential_low', 'residential_med', 'suburban', 'mixed'],
    preferredRoadTypes: ['street', 'avenue'],
    minRoadAccess: 0.08,
    preferredDensity: ['medium', 'low'],
    rarity: 0.35,
    maxPerCity: 3,
    lotSizeRange: { min: 24, max: 999 },
    composition: [{ childId: 'parking_lot', chance: 0.4, min: 0, max: 1 }],
    scoreWeights: W,
  }),
  def({
    id: 'factory',
    label: 'Fábrica',
    category: 'primary',
    footprint: { w: 8, h: 7 },
    color: 0x5d6d7e,
    allowedZones: ['industrial', 'periphery'],
    preferredRoadTypes: ['highway', 'main', 'avenue'],
    minRoadAccess: 0.1,
    preferredDensity: ['medium', 'low', 'sparse'],
    rarity: 0.35,
    maxPerCity: 5,
    lotSizeRange: { min: 40, max: 999 },
    isCityAnchor: true,
    composition: [
      { childId: 'depot', chance: 0.8, min: 1, max: 2 },
      { childId: 'parking_lot', chance: 0.7, min: 0, max: 1 },
      { childId: 'shed_annex', chance: 0.5, min: 0, max: 1 },
    ],
    scoreWeights: { ...W, road: 1.3, zone: 1.5 },
  }),
  def({
    id: 'warehouse',
    label: 'Depósito',
    category: 'primary',
    footprint: { w: 8, h: 6 },
    color: 0x6c7a89,
    allowedZones: ['industrial', 'commercial', 'periphery'],
    preferredRoadTypes: ['main', 'avenue', 'highway'],
    minRoadAccess: 0.12,
    preferredDensity: ['medium', 'low'],
    rarity: 0.45,
    lotSizeRange: { min: 40, max: 999 },
    composition: [{ childId: 'parking_lot', chance: 0.4, min: 0, max: 1 }],
    scoreWeights: W,
  }),
  def({
    id: 'industrial_yard',
    label: 'Área industrial',
    category: 'primary',
    footprint: { w: 9, h: 9 },
    color: 0x566573,
    allowedZones: ['industrial'],
    preferredRoadTypes: ['highway', 'main'],
    minRoadAccess: 0.1,
    preferredDensity: ['low', 'medium'],
    rarity: 0.3,
    maxPerCity: 3,
    lotSizeRange: { min: 70, max: 999 },
    composition: [
      { childId: 'depot', chance: 0.7, min: 0, max: 2 },
      { childId: 'workshop_annex', chance: 0.5, min: 0, max: 1 },
    ],
    scoreWeights: W,
  }),
  def({
    id: 'shed',
    label: 'Galpão',
    category: 'primary',
    footprint: { w: 6, h: 5 },
    color: 0x797d7f,
    allowedZones: ['industrial', 'periphery', 'rural'],
    preferredRoadTypes: ['street', 'main', 'residential'],
    minRoadAccess: 0.05,
    preferredDensity: ['low', 'sparse'],
    rarity: 0.5,
    lotSizeRange: { min: 24, max: 999 },
    scoreWeights: W,
  }),
  def({
    id: 'workshop',
    label: 'Oficina',
    category: 'primary',
    footprint: { w: 4, h: 4 },
    color: 0xb7950b,
    allowedZones: ['industrial', 'commercial', 'periphery', 'mixed'],
    preferredRoadTypes: ['street', 'avenue'],
    minRoadAccess: 0.1,
    preferredDensity: ['medium', 'low'],
    rarity: 0.5,
    lotSizeRange: { min: 14, max: 999 },
    composition: [{ childId: 'storage', chance: 0.4, min: 0, max: 1 }],
    scoreWeights: W,
  }),
  def({
    id: 'mechanic',
    label: 'Oficina mecânica',
    category: 'primary',
    footprint: { w: 5, h: 4 },
    color: 0x95a5a6,
    allowedZones: ['commercial', 'industrial', 'periphery'],
    preferredRoadTypes: ['street', 'avenue', 'main'],
    minRoadAccess: 0.12,
    preferredDensity: ['medium', 'low'],
    rarity: 0.45,
    lotSizeRange: { min: 18, max: 999 },
    composition: [{ childId: 'garage', chance: 0.6, min: 0, max: 1 }],
    scoreWeights: W,
  }),
  def({
    id: 'farm',
    label: 'Fazenda',
    category: 'primary',
    footprint: { w: 10, h: 8 },
    color: 0x9a7b4f,
    allowedZones: ['rural'],
    preferredRoadTypes: ['residential', 'street', 'main'],
    minRoadAccess: 0.05,
    preferredDensity: ['sparse', 'low'],
    rarity: 0.4,
    maxPerCity: 6,
    lotSizeRange: { min: 60, max: 999 },
    isCityAnchor: true,
    composition: [
      { childId: 'barn', chance: 0.9, min: 1, max: 1 },
      { childId: 'silo', chance: 0.7, min: 0, max: 2 },
      { childId: 'stable', chance: 0.5, min: 0, max: 1 },
      { childId: 'shed_annex', chance: 0.5, min: 0, max: 1 },
    ],
    scoreWeights: { ...W, zone: 1.6, center: -0.5 },
  }),
  def({
    id: 'farmhouse',
    label: 'Casa de fazenda',
    category: 'primary',
    footprint: { w: 5, h: 4 },
    color: 0xc9a66b,
    allowedZones: ['rural', 'periphery'],
    preferredRoadTypes: ['residential', 'street'],
    minRoadAccess: 0.05,
    preferredDensity: ['sparse', 'low'],
    rarity: 0.5,
    lotSizeRange: { min: 20, max: 999 },
    composition: [
      { childId: 'garage', chance: 0.4, min: 0, max: 1 },
      { childId: 'shed_annex', chance: 0.5, min: 0, max: 1 },
    ],
    scoreWeights: W,
  }),
  def({
    id: 'parking',
    label: 'Estacionamento',
    category: 'primary',
    footprint: { w: 6, h: 5 },
    color: 0x4a4a4a,
    allowedZones: ['commercial', 'center', 'industrial', 'mixed'],
    preferredRoadTypes: ['avenue', 'street', 'main'],
    minRoadAccess: 0.15,
    preferredDensity: ['high', 'medium'],
    rarity: 0.4,
    lotSizeRange: { min: 24, max: 999 },
    scoreWeights: W,
  }),
  // Secondaries / annexes
  def({
    id: 'garage',
    label: 'Garagem',
    category: 'secondary',
    footprint: { w: 3, h: 2 },
    color: 0x7b6b5a,
    allowedZones: [
      'residential_low',
      'residential_med',
      'suburban',
      'rural',
      'industrial',
    ],
    preferredRoadTypes: ['residential', 'street'],
    minRoadAccess: 0,
    preferredDensity: ['low', 'medium', 'sparse'],
    rarity: 1,
    lotSizeRange: { min: 0, max: 999 },
    scoreWeights: W,
  }),
  def({
    id: 'barn',
    label: 'Celeiro',
    category: 'secondary',
    footprint: { w: 4, h: 3 },
    color: 0x8d6e63,
    allowedZones: ['rural'],
    preferredRoadTypes: ['residential', 'street'],
    minRoadAccess: 0,
    preferredDensity: ['sparse', 'low'],
    rarity: 1,
    lotSizeRange: { min: 0, max: 999 },
    scoreWeights: W,
  }),
  def({
    id: 'stable',
    label: 'Estábulo',
    category: 'secondary',
    footprint: { w: 4, h: 3 },
    color: 0xa1887f,
    allowedZones: ['rural'],
    preferredRoadTypes: ['residential'],
    minRoadAccess: 0,
    preferredDensity: ['sparse'],
    rarity: 1,
    lotSizeRange: { min: 0, max: 999 },
    scoreWeights: W,
  }),
  def({
    id: 'silo',
    label: 'Silo',
    category: 'secondary',
    footprint: { w: 2, h: 2 },
    color: 0xb0bec5,
    allowedZones: ['rural', 'industrial'],
    preferredRoadTypes: ['residential', 'street'],
    minRoadAccess: 0,
    preferredDensity: ['sparse', 'low'],
    rarity: 1,
    lotSizeRange: { min: 0, max: 999 },
    scoreWeights: W,
  }),
  def({
    id: 'depot',
    label: 'Depósito anexo',
    category: 'secondary',
    footprint: { w: 3, h: 3 },
    color: 0x607d8b,
    allowedZones: ['industrial', 'commercial', 'center', 'mixed'],
    preferredRoadTypes: ['avenue', 'street'],
    minRoadAccess: 0,
    preferredDensity: ['medium', 'high', 'low'],
    rarity: 1,
    lotSizeRange: { min: 0, max: 999 },
    scoreWeights: W,
  }),
  def({
    id: 'shed_annex',
    label: 'Galpão anexo',
    category: 'secondary',
    footprint: { w: 3, h: 2 },
    color: 0x6d4c41,
    allowedZones: ['rural', 'industrial', 'periphery', 'residential_low'],
    preferredRoadTypes: ['residential', 'street'],
    minRoadAccess: 0,
    preferredDensity: ['low', 'sparse'],
    rarity: 1,
    lotSizeRange: { min: 0, max: 999 },
    scoreWeights: W,
  }),
  def({
    id: 'workshop_annex',
    label: 'Oficina anexa',
    category: 'secondary',
    footprint: { w: 3, h: 2 },
    color: 0x9e9d24,
    allowedZones: ['industrial', 'commercial', 'periphery'],
    preferredRoadTypes: ['street', 'main'],
    minRoadAccess: 0,
    preferredDensity: ['medium', 'low'],
    rarity: 1,
    lotSizeRange: { min: 0, max: 999 },
    scoreWeights: W,
  }),
  def({
    id: 'storage',
    label: 'Armazém',
    category: 'secondary',
    footprint: { w: 2, h: 2 },
    color: 0x78909c,
    allowedZones: [
      'commercial',
      'industrial',
      'residential_med',
      'mixed',
      'center',
    ],
    preferredRoadTypes: ['street'],
    minRoadAccess: 0,
    preferredDensity: ['high', 'medium', 'low'],
    rarity: 1,
    lotSizeRange: { min: 0, max: 999 },
    scoreWeights: W,
  }),
  def({
    id: 'parking_lot',
    label: 'Estacionamento',
    category: 'secondary',
    footprint: { w: 4, h: 3 },
    color: 0x424242,
    allowedZones: [
      'commercial',
      'center',
      'industrial',
      'mixed',
      'residential_med',
    ],
    preferredRoadTypes: ['avenue', 'street'],
    minRoadAccess: 0,
    preferredDensity: ['high', 'medium'],
    rarity: 1,
    lotSizeRange: { min: 0, max: 999 },
    scoreWeights: W,
  }),
  // Exploration POIs
  def({
    id: 'abandoned_car',
    label: 'Carro abandonado',
    category: 'exploration',
    footprint: { w: 2, h: 1 },
    color: 0xff7043,
    allowedZones: [
      'periphery',
      'industrial',
      'suburban',
      'commercial',
      'rural',
      'residential_low',
    ],
    preferredRoadTypes: ['street', 'residential', 'main'],
    minRoadAccess: 0,
    preferredDensity: ['low', 'sparse', 'medium'],
    rarity: 1,
    lotSizeRange: { min: 0, max: 999 },
    scoreWeights: W,
  }),
  def({
    id: 'trash_bin',
    label: 'Lixeira',
    category: 'exploration',
    footprint: { w: 1, h: 1 },
    color: 0x66bb6a,
    allowedZones: [
      'residential_med',
      'residential_low',
      'commercial',
      'mixed',
      'center',
    ],
    preferredRoadTypes: ['street', 'residential'],
    minRoadAccess: 0,
    preferredDensity: ['high', 'medium', 'low'],
    rarity: 1,
    lotSizeRange: { min: 0, max: 999 },
    scoreWeights: W,
  }),
  def({
    id: 'malas',
    label: 'Malas',
    category: 'exploration',
    footprint: { w: 2, h: 1 },
    color: 0x43a047,
    allowedZones: ['commercial', 'industrial', 'mixed', 'center'],
    preferredRoadTypes: ['street', 'avenue'],
    minRoadAccess: 0,
    preferredDensity: ['high', 'medium'],
    rarity: 1,
    lotSizeRange: { min: 0, max: 999 },
    scoreWeights: W,
  }),
  def({
    id: 'container',
    label: 'Contêiner',
    category: 'exploration',
    footprint: { w: 2, h: 1 },
    color: 0x26a69a,
    allowedZones: ['industrial', 'periphery', 'commercial'],
    preferredRoadTypes: ['main', 'street'],
    minRoadAccess: 0,
    preferredDensity: ['low', 'medium'],
    rarity: 1,
    lotSizeRange: { min: 0, max: 999 },
    scoreWeights: W,
  }),
  def({
    id: 'locker',
    label: 'Armário',
    category: 'exploration',
    footprint: { w: 1, h: 1 },
    color: 0x8d6e63,
    allowedZones: ['industrial', 'commercial', 'center', 'mixed'],
    preferredRoadTypes: ['street'],
    minRoadAccess: 0,
    preferredDensity: ['high', 'medium'],
    rarity: 1,
    lotSizeRange: { min: 0, max: 999 },
    scoreWeights: W,
  }),
  def({
    id: 'crate',
    label: 'Caixa',
    category: 'exploration',
    footprint: { w: 1, h: 1 },
    color: 0xa1887f,
    allowedZones: [
      'industrial',
      'commercial',
      'periphery',
      'rural',
      'residential_low',
    ],
    preferredRoadTypes: ['street', 'residential'],
    minRoadAccess: 0,
    preferredDensity: ['medium', 'low', 'sparse'],
    rarity: 1,
    lotSizeRange: { min: 0, max: 999 },
    scoreWeights: W,
  }),
  def({
    id: 'corpse',
    label: 'Cadáver',
    category: 'exploration',
    footprint: { w: 1, h: 1 },
    color: 0xef5350,
    allowedZones: [
      'periphery',
      'industrial',
      'rural',
      'suburban',
      'residential_low',
    ],
    preferredRoadTypes: ['residential', 'street'],
    minRoadAccess: 0,
    preferredDensity: ['sparse', 'low'],
    rarity: 0.7,
    lotSizeRange: { min: 0, max: 999 },
    scoreWeights: W,
  }),
  def({
    id: 'backpack',
    label: 'Mochila',
    category: 'exploration',
    footprint: { w: 1, h: 1 },
    color: 0x42a5f5,
    allowedZones: [
      'residential_med',
      'suburban',
      'commercial',
      'periphery',
      'center',
    ],
    preferredRoadTypes: ['street', 'residential'],
    minRoadAccess: 0,
    preferredDensity: ['medium', 'low'],
    rarity: 0.8,
    lotSizeRange: { min: 0, max: 999 },
    scoreWeights: W,
  }),
  def({
    id: 'car_trunk',
    label: 'Porta-malas',
    category: 'exploration',
    footprint: { w: 1, h: 1 },
    color: 0xffa726,
    allowedZones: ['periphery', 'suburban', 'commercial', 'industrial'],
    preferredRoadTypes: ['street', 'residential', 'main'],
    minRoadAccess: 0,
    preferredDensity: ['low', 'medium'],
    rarity: 0.7,
    lotSizeRange: { min: 0, max: 999 },
    scoreWeights: W,
  }),
  def({
    id: 'generator',
    label: 'Gerador',
    category: 'exploration',
    footprint: { w: 1, h: 1 },
    color: 0xffee58,
    allowedZones: ['industrial', 'center', 'commercial', 'rural'],
    preferredRoadTypes: ['street', 'avenue'],
    minRoadAccess: 0,
    preferredDensity: ['medium', 'low', 'high'],
    rarity: 0.6,
    lotSizeRange: { min: 0, max: 999 },
    scoreWeights: W,
  }),
  def({
    id: 'machine',
    label: 'Máquina',
    category: 'exploration',
    footprint: { w: 2, h: 1 },
    color: 0xbdbdbd,
    allowedZones: ['industrial', 'periphery', 'rural'],
    preferredRoadTypes: ['street', 'main'],
    minRoadAccess: 0,
    preferredDensity: ['low', 'sparse'],
    rarity: 0.7,
    lotSizeRange: { min: 0, max: 999 },
    scoreWeights: W,
  }),
];

const byId = new Map(STRUCTURE_DEFINITIONS.map((d) => [d.id, d]));

export function getStructureDef(id: string): StructureDefinition {
  const d = byId.get(id);
  if (!d) throw new Error(`StructureDefinition not found: ${id}`);
  return d;
}

export function getPrimaries(): StructureDefinition[] {
  return STRUCTURE_DEFINITIONS.filter((d) => d.category === 'primary');
}

export function getSecondaries(): StructureDefinition[] {
  return STRUCTURE_DEFINITIONS.filter((d) => d.category === 'secondary');
}

export function getExplorations(): StructureDefinition[] {
  return STRUCTURE_DEFINITIONS.filter((d) => d.category === 'exploration');
}

export function getCityAnchors(): StructureDefinition[] {
  return STRUCTURE_DEFINITIONS.filter((d) => d.isCityAnchor);
}

/** Quotas mínimas de âncoras por tamanho de cidade. */
export const ANCHOR_QUOTAS: Record<
  'small' | 'medium' | 'large',
  Partial<Record<string, number>>
> = {
  small: {
    hospital: 0,
    clinic: 1,
    police: 1,
    school: 1,
    market: 1,
    gas_station: 1,
    farm: 1,
    factory: 0,
  },
  medium: {
    hospital: 1,
    clinic: 1,
    police: 1,
    school: 2,
    market: 2,
    gas_station: 2,
    farm: 2,
    factory: 1,
    fire_station: 1,
  },
  large: {
    hospital: 2,
    clinic: 2,
    police: 2,
    school: 3,
    market: 3,
    gas_station: 3,
    farm: 3,
    factory: 2,
    fire_station: 1,
    hotel: 1,
  },
};
