import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { mergeProfiles, metricsToProfile } from './buildProfiles';
import type { CityMetricsReport } from './metrics/report';
import { CITY_TARGETS } from './cities';
import type { CityProfile } from '../../../src/world/profiles/types';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const RAW_DIR = path.resolve(__dirname, '../../../profiles/raw-metrics');
const OUT_DIR = path.resolve(__dirname, '../../../profiles/derived');
const GEN_DIR = path.resolve(
  __dirname,
  '../../../src/world/profiles/generated',
);
const GEN_DATA = path.join(GEN_DIR, 'data');
const GEN_TS = path.join(GEN_DIR, 'OsmProfiles.ts');

function loadReports(): CityMetricsReport[] {
  if (!fs.existsSync(RAW_DIR)) return [];
  return fs
    .readdirSync(RAW_DIR)
    .filter((f) => f.endsWith('.metrics.json'))
    .map((f) => JSON.parse(fs.readFileSync(path.join(RAW_DIR, f), 'utf8')) as CityMetricsReport);
}

function writeProfileJson(profile: CityProfile): string[] {
  fs.mkdirSync(OUT_DIR, { recursive: true });
  fs.mkdirSync(GEN_DATA, { recursive: true });
  const name = `${profile.id}.json`;
  const a = path.join(OUT_DIR, name);
  const b = path.join(GEN_DATA, name);
  const body = JSON.stringify(profile, null, 2);
  fs.writeFileSync(a, body, 'utf8');
  fs.writeFileSync(b, body, 'utf8');
  return [a, b];
}

function writeGeneratedTs(profiles: CityProfile[]): void {
  fs.mkdirSync(GEN_DIR, { recursive: true });
  const imports = profiles
    .map((p) => `import ${p.id}Json from './data/${p.id}.json';`)
    .join('\n');

  const body = `/* AUTO-GENERATED by npm run build:profiles — do not edit by hand */
import type { CityProfile } from '../types';
import { registerProfile } from '../registry';

${imports}

const profiles: CityProfile[] = [
${profiles.map((p) => `  ${p.id}Json as unknown as CityProfile,`).join('\n')}
];

export function registerOsmDerivedProfiles(): void {
  for (const p of profiles) {
    registerProfile(p);
  }
}

export const OSM_DERIVED_PROFILE_IDS = ${JSON.stringify(profiles.map((p) => p.id))} as const;
`;

  fs.writeFileSync(GEN_TS, body, 'utf8');
}

function main(): void {
  const reports = loadReports();
  if (reports.length === 0) {
    console.error(`Nenhum relatório em ${RAW_DIR}. Rode analyze:city primeiro.`);
    process.exit(1);
  }

  const perCity = reports.map((r) => metricsToProfile(r));
  const written: string[] = [];
  for (const p of perCity) {
    written.push(...writeProfileJson(p));
  }

  const observed = perCity.filter((p) => p.buildings.meta.quality === 'observed');
  const allForRegistry = [...observed];

  if (observed.length >= 1) {
    const sources = reports
      .filter((r) =>
        observed.some((p) => p.description.includes(r.cityId)),
      )
      .map((r) => r.cityId);

    const sizeHints = sources.map((id) => CITY_TARGETS[id]?.sizeHint ?? 'medium');
    const label =
      observed.length === 1
        ? `Brazilian medium city (from ${observed[0]!.id} only — expand sample)`
        : `Brazilian aggregate (${observed.length} cities: ${sizeHints.join(', ')})`;

    const merged = mergeProfiles(observed, 'BrazilianMediumCity', label);
    written.push(...writeProfileJson(merged));
    allForRegistry.push(merged);
  }

  writeGeneratedTs(allForRegistry);

  console.log('Profiles escritos:');
  for (const w of written) console.log(`  ${w}`);
  console.log(`TS registry: ${GEN_TS}`);
  console.log(`Amostra: ${reports.map((r) => r.cityId).join(', ')}`);
}

main();
